on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"
      - "**/compile_linux.yml"
      - "**/build_flatpak.yml"
      - "**/.all-contributorsrc"
      - "**/upload_full_src.yml"
      - "**/windows_debug.yml"
      - "**/upload_binaries_to_draft.yml"
  pull_request:
    branches: [master]

name: Build on Windows
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install OpenSSL
        uses: crazy-max/ghaction-chocolatey@v3.3.0
        with:
          args: install openssl -y

      - name: Compile Embed-Helper
        run: "cd src/ui/impl/webview/lib/webviewpp/embed-helper && mkdir build && cd build && cmake .. && cmake --build . --config Release && cd Release && ./embed_helper ../../../../soundux-ui"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -DEMBED_PATH=src/ui/impl/webview/lib/webviewpp/embed-helper/build/Release && cmake --build . --config Release"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Release
          path: build/Release

      - name: Install InnoSetup
        uses: crazy-max/ghaction-chocolatey@v3.3.0
        with:
          args: install innosetup -y

      - name: Install Sed
        uses: crazy-max/ghaction-chocolatey@v3.3.0
        with:
          args: install sed -y

      - name: Run Sed
        run: '&"${Env:ProgramData}\chocolatey\bin\sed.exe" -i ''s%\$PATH%D:\\a\\Soundux\\Soundux%'' deployment/innosetup/Soundux.iss'

      - name: Run InnoSetup
        run: '&"${Env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" deployment/innosetup/Soundux.iss'

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Installer
          path: deployment/innosetup/Output/setup.exe
