on: workflow_dispatch

name: Debug on Windows
jobs:
    debug-windows:
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                language: ["cpp"]

        steps:
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.5

            - name: Setup NuGet.exe for use with actions
              uses: NuGet/setup-nuget@v2.0.1

            - name: Checkout
              uses: actions/checkout@v2.3.4
              with:
                  submodules: recursive

            - name: Install OpenSSL
              uses: crazy-max/ghaction-chocolatey@v1.5.0
              with:
                  args: install openssl -y

            - name: Add NuGet Remote
              run: "nuget.exe sources Add -Name NuGetRemote -Source https://api.nuget.org/v3/index.json"

            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
              with:
                limit-access-to-actor: true
              continue-on-error: true